# netlify.toml
[build]
  command = "pip install -r requirements.txt"
  functions = "functions/"
  publish = "static/" # A dummy folder for Netlify to publish

[functions]
  included_files = ["app.py", "templates/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200